/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MgAmbulanceWlApp {
        "ambulanceId": string;
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
    }
    interface MgAmbulanceWlEditor {
        "ambulanceId": string;
        "apiBase": string;
        "entryId": string;
    }
    interface MgAmbulanceWlList {
        "ambulanceId": string;
        "apiBase": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface MgAmbulanceWlEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMgAmbulanceWlEditorElement;
}
export interface MgAmbulanceWlListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMgAmbulanceWlListElement;
}
declare global {
    interface HTMLMgAmbulanceWlAppElement extends Components.MgAmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLMgAmbulanceWlAppElement: {
        prototype: HTMLMgAmbulanceWlAppElement;
        new (): HTMLMgAmbulanceWlAppElement;
    };
    interface HTMLMgAmbulanceWlEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLMgAmbulanceWlEditorElement extends Components.MgAmbulanceWlEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMgAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLMgAmbulanceWlEditorElement, ev: MgAmbulanceWlEditorCustomEvent<HTMLMgAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMgAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLMgAmbulanceWlEditorElement, ev: MgAmbulanceWlEditorCustomEvent<HTMLMgAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMgAmbulanceWlEditorElement: {
        prototype: HTMLMgAmbulanceWlEditorElement;
        new (): HTMLMgAmbulanceWlEditorElement;
    };
    interface HTMLMgAmbulanceWlListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLMgAmbulanceWlListElement extends Components.MgAmbulanceWlList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMgAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLMgAmbulanceWlListElement, ev: MgAmbulanceWlListCustomEvent<HTMLMgAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMgAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLMgAmbulanceWlListElement, ev: MgAmbulanceWlListCustomEvent<HTMLMgAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMgAmbulanceWlListElement: {
        prototype: HTMLMgAmbulanceWlListElement;
        new (): HTMLMgAmbulanceWlListElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "mg-ambulance-wl-app": HTMLMgAmbulanceWlAppElement;
        "mg-ambulance-wl-editor": HTMLMgAmbulanceWlEditorElement;
        "mg-ambulance-wl-list": HTMLMgAmbulanceWlListElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MgAmbulanceWlApp {
        "ambulanceId"?: string;
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
    }
    interface MgAmbulanceWlEditor {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: MgAmbulanceWlEditorCustomEvent<string>) => void;
    }
    interface MgAmbulanceWlList {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "onEntry-clicked"?: (event: MgAmbulanceWlListCustomEvent<string>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }

    interface MgAmbulanceWlAppAttributes {
        "basePath": string;
        "apiBase": string;
        "ambulanceId": string;
    }
    interface MgAmbulanceWlEditorAttributes {
        "entryId": string;
        "ambulanceId": string;
        "apiBase": string;
    }
    interface MgAmbulanceWlListAttributes {
        "apiBase": string;
        "ambulanceId": string;
    }
    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }

    interface IntrinsicElements {
        "mg-ambulance-wl-app": Omit<MgAmbulanceWlApp, keyof MgAmbulanceWlAppAttributes> & { [K in keyof MgAmbulanceWlApp & keyof MgAmbulanceWlAppAttributes]?: MgAmbulanceWlApp[K] } & { [K in keyof MgAmbulanceWlApp & keyof MgAmbulanceWlAppAttributes as `attr:${K}`]?: MgAmbulanceWlAppAttributes[K] } & { [K in keyof MgAmbulanceWlApp & keyof MgAmbulanceWlAppAttributes as `prop:${K}`]?: MgAmbulanceWlApp[K] };
        "mg-ambulance-wl-editor": Omit<MgAmbulanceWlEditor, keyof MgAmbulanceWlEditorAttributes> & { [K in keyof MgAmbulanceWlEditor & keyof MgAmbulanceWlEditorAttributes]?: MgAmbulanceWlEditor[K] } & { [K in keyof MgAmbulanceWlEditor & keyof MgAmbulanceWlEditorAttributes as `attr:${K}`]?: MgAmbulanceWlEditorAttributes[K] } & { [K in keyof MgAmbulanceWlEditor & keyof MgAmbulanceWlEditorAttributes as `prop:${K}`]?: MgAmbulanceWlEditor[K] };
        "mg-ambulance-wl-list": Omit<MgAmbulanceWlList, keyof MgAmbulanceWlListAttributes> & { [K in keyof MgAmbulanceWlList & keyof MgAmbulanceWlListAttributes]?: MgAmbulanceWlList[K] } & { [K in keyof MgAmbulanceWlList & keyof MgAmbulanceWlListAttributes as `attr:${K}`]?: MgAmbulanceWlListAttributes[K] } & { [K in keyof MgAmbulanceWlList & keyof MgAmbulanceWlListAttributes as `prop:${K}`]?: MgAmbulanceWlList[K] };
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mg-ambulance-wl-app": LocalJSX.IntrinsicElements["mg-ambulance-wl-app"] & JSXBase.HTMLAttributes<HTMLMgAmbulanceWlAppElement>;
            "mg-ambulance-wl-editor": LocalJSX.IntrinsicElements["mg-ambulance-wl-editor"] & JSXBase.HTMLAttributes<HTMLMgAmbulanceWlEditorElement>;
            "mg-ambulance-wl-list": LocalJSX.IntrinsicElements["mg-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLMgAmbulanceWlListElement>;
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
